-- AlterTable
ALTER TABLE `users` ADD COLUMN `address` TEXT NULL,
    ADD COLUMN `amount` TEXT NULL,
    ADD COLUMN `donation` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `donation_audio` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `email` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `is_paid` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `nityaniyam_paid` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `otp` VARCHAR(255) NULL,
    ADD COLUMN `part_1` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `part_2` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `upasana_paid` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `updated_at` DATETIME(3) NULL,
    ADD COLUMN `updated_at2` DATETIME(3) NULL;
